#!/usr/bin/env bash

MAIN_COLOR=f60761ff
i3lock \
    --ignore-empty-password \
    --verif-text="" \
    --wrong-text="" \
    --ring-color=$MAIN_COLOR \
    --ringver-color=$MAIN_COLOR \
    --insidever-color=$MAIN_COLOR \
    --verif-color=$MAIN_COLOR \
    --wrong-color=$MAIN_COLOR \
    --image=/home/neo/Pictures/lock_screen.jpg \
    --fill \
    --color=000000ff
